[package]
name = "sht2x"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = "0.1.0"

[dev-dependencies]
linux-embedded-hal = "0.1.1"

[profile.release]
lto = true
